### ISSUE TITLE
didn't work: Thumbnails look the same.

### ISSUE THREAD

**Issue by DavidSmolinski** [elliotwaite/thumbnail-rating-bar-for-youtube#81] opened 2023-05-09 06:19 UTC
"Return YouTube Dislike" failed recently. It could be the same bug cause.

v1.8.7
Chrome v112.0.5615.165

**Comment by elliotwaite** [comment] 2023-05-10 17:18
Thanks for reporting this. I'm seeing the same thing, all the ratings bars have the same rating.

From looking at [Return YouTube Dislike's GitHub issues](https://github.com/Anarios/return-youtube-dislike/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), it looks like they are experiencing technical difficulties at the moment. This has happened in the past and the issue is usually resolved within a few days. Hopefully the ratings will back to normal soon.

**Comment by elliotwaite** [comment] 2023-05-12 16:28
It looks like they are working again, so I'm going to close this issue. But if for some reason they still aren't working for you, let me know.

**Closed by elliotwaite** 2023-05-12 16:28 UTC
