### ISSUE TITLE
Extensions shows wrong ratings

### ISSUE THREAD

**Issue by Liz-chan** [elliotwaite/thumbnail-rating-bar-for-youtube#4] opened 2018-07-01 07:25 UTC
Sometimes the extension gives a video the wrong rating, which is definitely not good since it could deter me from watching potential good videos in the future. These pictures should tell you what I mean.
![image](https://user-images.githubusercontent.com/18467466/42132053-36c84eea-7cde-11e8-8e3b-1135585dd134.png)
![image](https://user-images.githubusercontent.com/18467466/42132056-3e18600e-7cde-11e8-893e-ee859c02f6d5.png)
As you can see, it gives the video a completely wrong rating, and when you actually click on the video, it shows the correct rating. Any thoughts on why it does this?

Addition: It seems this doesn't happen on searches, but I just did a quick search for the same video.

**Comment by elliotwaite** [comment] 2018-07-01 07:54
Dang, that's really bad.

I recently fixed a bug that was occurring when trying to update over 50 thumbnails at once, which may have been related to this. Can you make sure you're on the latest version (at least 0.0.24), you can see the version in the chrome://extensions/ window if you turn on the "Developer mode" switch at the top right of the page.

Was that on a suggested video that it gave the wrong rating? If you are somehow able to figure out how to reproduce this so I can debug it, that'd be great. I'll try to see if I can get it to happen for me.

**Comment by Liz-chan** [comment] 2018-07-01 07:57
Yep, I'm on the latest version according to chrome. Checked and it said 0.0.24. Even on videos that aren't recommended to me, it still happens. Here it is with another video.
![image](https://user-images.githubusercontent.com/18467466/42132281-c92353bc-7ce2-11e8-9a51-d3a6a1ddb35a.png)
![image](https://user-images.githubusercontent.com/18467466/42132282-d214e378-7ce2-11e8-8069-1a22fabf389c.png)

**Comment by elliotwaite** [comment] 2018-07-01 08:02
Okay. Can you link me to the page where it occurred?

**Comment by Liz-chan** [comment] 2018-07-01 08:03
Sure, here you go.
https://youtu.be/CzueOh-d15M

**Comment by elliotwaite** [comment] 2018-07-01 08:11
Hmm, maybe.

When not in the incognito window, would it happen every time you reloaded that page for that thumbnail, or only some of the times?

**Comment by Liz-chan** [comment] 2018-07-01 08:13
Sorry if my edits were a bit confusing. When I said I refreshed the page I did it in the normal window, not the incognito one. I still have the same everything, so I don't know why it'd be different results.

**Comment by elliotwaite** [comment] 2018-07-01 08:20
Ah, ok. I'm about to head to bed, but I'll work on it more tomorrow. I'll try to add something in the next release that will make it easier to debug that issue when it happens, like some html tag data on the bar element that says which exact video ID the bar's data is for.

**Comment by Liz-chan** [comment] 2018-07-02 01:43
Damn it happened again, that's a shame. Would it help if I included a local copy of the page with my comment?
![image](https://user-images.githubusercontent.com/18467466/42141539-d62dbfbc-7d77-11e8-8b9e-ab5ae72d70a0.png)
![image](https://user-images.githubusercontent.com/18467466/42141545-dbdcf96e-7d77-11e8-927d-589862f8b4c7.png)

**Comment by elliotwaite** [comment] 2018-07-02 07:19
Yeah, I think it's unlikely that the Iridium extension would affect the rating bars.

Yeah, there isn't much info on the page at the moment to debug the issue, but in the next update, probably released tomorrow, I'll add in all the hidden meta data tags. Then if you see it happen again, you can just do a right click on the page, and then click inspect to bring up the elements tab in the developers console, then copy the entire html element and then paste it here, and hopefully that will help with figuring out what is going on. I'll let you know when I release that update.

Also, thank you for taking the time to help me debug this. I appreciate it.

**Comment by Liz-chan** [comment] 2018-07-02 07:21
Yea no problem, we have a similar goal, a bug-free extension 😄

**Comment by elliotwaite** [comment] 2018-07-03 10:59
Ah, I figured out what is happening. On a page change, sometimes some of the thumbnail elements don't get completely recreated. Instead, their internal video data just gets swapped out. So the rating bar doesn't get deleted and it just displays the rating for the video previously in that spot.

Working on a fix.

**Comment by Liz-chan** [comment] 2018-07-03 11:00
Oh sweet, glad you figured it out

**Comment by elliotwaite** [comment] 2018-07-04 11:45
Just released an update that should have fixed the issue (0.0.25). I was able to predictably reproduce the problem while debugging it by simply doing 2 different searches then pressing the back and forward history buttons to navigate between those two pages. But yeah, should be fixed now.

Let me know if you notice it messing up at still.

**Comment by Liz-chan** [comment] 2018-07-04 11:47
Thanks for taking the time to figure out the problem, and I'll let you know if I notice it again now. I just checked the version and it seems it already updated to .25, that was fast.

**Comment by elliotwaite** [comment] 2018-07-04 11:50
Nice. I was wondering how long it takes for updates to get to the users. I guess it happens pretty quickly.

**Comment by elliotwaite** [comment] 2018-07-05 10:39
I'm going to close this issue for now, but please reopen it if you ever notice it happening again.

**Comment by Liz-chan** [comment] 2018-07-06 00:06
![image](https://user-images.githubusercontent.com/18467466/42353512-e0a6c762-808e-11e8-8cb0-f88a7d62db5a.png)
![image](https://user-images.githubusercontent.com/18467466/42353518-e7e9fd96-808e-11e8-88bd-4012175c37e3.png)
https://www.youtube.com/channel/UCf_67twWOb9eYH-HX562r6A/videos

It doesn't change when you refresh.

**Comment by elliotwaite** [comment] 2018-07-06 01:45
Hmm, that's a strange one. The data returned by the YouTube Data API says that video has 67 dislikes.

```
{
 "kind": "youtube#videoListResponse",
 "etag": "\"DuHzAJ-eQIiCIp7p4ldoVcVAOeY/cmQM5MaVsgy_hu9deDiU8VUoimE\"",
 "pageInfo": {
  "totalResults": 1,
  "resultsPerPage": 1
 },
 "items": [
  {
   "kind": "youtube#video",
   "etag": "\"DuHzAJ-eQIiCIp7p4ldoVcVAOeY/Z-ivz1gfcn62KUm6pi9rIDp-IRg\"",
   "id": "Z_-XeSa9Fo0",
   "statistics": {
    "viewCount": "3713",
    "likeCount": "337",
    "dislikeCount": "67",
    "favoriteCount": "0",
    "commentCount": "139"
   }
  }
 ]
}
```

This might be a bug with the YouTube Data API. I created a new issue for it on Google's issue tracker:
https://issuetracker.google.com/issues/111179602

We'll see what they say.

**Comment by Gitoffthelawn** [comment] 2019-04-04 07:41
Any update on this?

**Comment by elliotwaite** [comment] 2019-05-03 03:26
It looks like a Googler has been assigned to the issue in the bug tracker, but not sure if there's been any other progress yet. The issue can be tracked here: https://issuetracker.google.com/issues/111179602

**Comment by elliotwaite** [comment] 2022-03-15 01:43
Since this extension no longer uses the YouTube Data API, I going to close this issue since it no longer applies. But thank you for reporting this issue.

**Closed by elliotwaite** 2022-03-15 01:43 UTC
Labels: bug
