### ISSUE TITLE
(Request) Show video page rating bar when using old-style YouTube layout

### ISSUE THREAD

**Issue by GranTurismo364** [elliotwaite/thumbnail-rating-bar-for-youtube#76] opened 2022-08-02 19:16 UTC
I use custom CSS (via Stylish) to get the old layout of YouTube back, but doing so removes the coloured bar under the like/dislike buttons. Is there a way to return/add compatibility with the old layout?

Thanks!

**Comment by elliotwaite** [comment] 2022-08-02 19:17
Can you share a screenshot?

**Comment by GranTurismo364** [comment] 2022-08-02 19:22
![firefox_OOgg5aQuqo](https://user-images.githubusercontent.com/90652911/182456368-d0d9c87d-b5ad-4775-a447-7ab67ea48570.png)

**Comment by elliotwaite** [comment] 2022-08-02 19:32
That rating bar, the one on the video page, is added by the Return YouTube Dislike extension, so I think it's an incompatibility between your custom CSS and that extension. I don't know much about how their extension works, but you could potentially check out their [code base](https://github.com/Anarios/return-youtube-dislike) to try to figure out how their code adds that rating bar and what is causing the incompatibility.

**Comment by GranTurismo364** [comment] 2022-08-02 19:46
Thank you, I'll take a look at that and see if I can do anything, or if anybody else is experiencing the same.

**Comment by elliotwaite** [comment] 2022-08-02 19:50
Okay, sounds good. I'm going to close this issue for now since the cause seems to be unrelated to this extension, but feel free to leave any more comments if you have any more questions for me about this.

**Closed by elliotwaite** 2022-08-02 19:50 UTC
